### ISSUE TITLE
Create blacklist of websites that won't be zimmed up.

### ISSUE THREAD

**Issue by Popolechien** [openzim/zimit#206] opened 2023-08-21 10:22 UTC
Following up on #205 I think we now know that there are a bunch of websites that are regularly being requested (the latest being commons.wikimedia.org, but others like "google.com" or youtube also come up). These requests take time and resources to handle, so we should as well come up with an _ad hoc_ (and fairly easy to expand) blacklist that would tell users that nope, we won't proceed.

**Comment by rgaudin** [comment] 2023-08-21 10:24
Duplicate of https://github.com/openzim/zimit-frontend/issues/28

**Closed by rgaudin** 2023-08-21 10:24 UTC
Labels: enhancement
