### ISSUE TITLE
Army Pub Not Working 

### ISSUE THREAD

**Issue by scoutg85** [openzim/zimit#152] opened 2022-08-09 03:17 UTC
Army Pub was working fine for awhile but recently stopped working on newer images. It's not working on Chrome and Edge; I have not tested other browsers.

**Comment by rgaudin** [comment] 2022-08-09 07:08
OK, I move the zimfarm recipe and July ZIM to dev so the library and cardshop only offers the June version.

Now for this ticket to be actionable, we'll need more details than «it's not working» 😉

https://github.com/openzim/warc2zim/issues/97

**Comment by scoutg85** [comment] 2022-08-09 17:38
I'll try remaking an image to see if it works now.

Regarding the issue, nothing loads. When I click Army Pub in the menu
selection, it initiates opening the page but gets stuck on loading the
content (nothing shows). I'll tried it on multiple platforms/os (ipad,
iphone, android devices, windows 10, windows 11), and experienced the same
issue even after re-creating and redownloading the image. I'll try again
with the latest change you made.

Thank you!

**Comment by Jaifroid** [comment] 2022-08-14 05:09
@scoutg85 Is this in Kiwix desktop, and if so, which version? I did quite a lot of testing of the July armypubs ZIM in both Kiwix Desktop and in the PWA (https://pwa.kiwix.org) when I was fixing the PWA code. I don't have access to the ZIM on my travelling laptop to corroborate, but both readers were able to access and display this ZIM fine (for me) a couple of weeks ago.

**Comment by Popolechien** [comment] 2022-08-14 08:27
@Jaifroid I think this is on Kiwix-serve (hotspot)

**Comment by Jaifroid** [comment] 2022-09-05 19:22
Just circling back to this issue, assuming this is a report concerning the Type 1 ZIM `armypubs_en_all_2022-06.zim`, I can't reproduce any issue in either Kiwix Serve (image left below) or in https://pwa.kiwix.org (image right below). Bottom image shows diagnostics for the ZIM object. I wonder if OP was correctly accessing the ZIM from http://localhost:8080 (or whatever the set port is on their machine).

![image](https://user-images.githubusercontent.com/4304337/188504561-4619cf52-7e79-4270-a513-4a6e261ba87b.png)

![image](https://user-images.githubusercontent.com/4304337/188504596-c0681d9f-c173-4b25-ba09-7f677b35032f.png)

**Comment by scoutg85** [comment] 2022-09-10 19:35
Sorry for the delayed response. I made another hotspot image 2 weeks ago at https://cardshop.hotspot.kiwix.org/  . The image that was generate still doesn't have a functioning army pubs; it fails to load the page on multiple OS (apple, windows, android).

**Comment by rgaudin** [comment] 2022-09-10 20:08
@scoutg85 I think this is #154. Can you try with a fresh browser to confirm? Easiest is to download a different one but you can clear **ALL** data as well.

**Comment by rgaudin** [comment] 2022-09-12 08:29
@kelson42 I am closing this as the ZIM is working fine albeit #154 which is not specific to this ZIM.

**Closed by rgaudin** 2022-09-12 08:29 UTC
Labels: bug
