### ISSUE TITLE
TV Tropes broken file

### ISSUE THREAD

**Issue by RavanJAltaie** [openzim/zimit#209] opened 2023-08-25 13:01 UTC
The TV tropes file is should be successful, when I open it without internet (Offline) it doesn't work.
Same file I open it when the internet is there everything is working fine.
Can you double check the recipe and file please?
https://farm.openzim.org/recipes/tvtropes
https://download.kiwix.org/zim/zimit/tvtropes_en_all_2023-08.zim

**Comment by rgaudin** [comment] 2023-08-25 14:25
What does “doesn't work” mean? I can't help if I don't know what the problem is. I tested on library.kiwix.org and I didn't find any external request. I downloaded and tested with kiwix serve offline as well.

In the future, please assign @benoit74 for zimit-related ticket as well

**Comment by Popolechien** [comment] 2023-08-25 14:39
@rgaudin If you go to https://library.kiwix.org/viewer#tvtropes_en_all_2023-08/A/tvtropes.org/ (or really click any page from the landing) and then click on the first link (here `Cyborging`) you will get a 403 message.

**Comment by rgaudin** [comment] 2023-08-25 14:45
Indeed a good number of those are visible. The message is pretty clear: the website blocked the scraper because it was generating too much traffic. The recipe accepts a `--delay` option which can be used to slow down the scraper (by waiting this amount of seconds in-between pages). You can try to set it to `1` and relaunch

**Comment by kelson42** [comment] 2023-08-27 03:31
> The TV tropes file is should be successful, when I open it without internet (Offline) it doesn't work.

@RavanJAltaie Thank you for the bug report. I want to emphasis that it is **essential** that bug report are precise, we have a [very instructive HOWTO helping to make good bug report](https://github.com/kiwix/overview/blob/main/REPORT_BUG.md). Please read it. I always recommend to print-it and then for the next 50 tickets, always check that things have been done right, then you won't need it anymore.

**Comment by kelson42** [comment] 2023-08-27 03:32
Solution seems straight to me, closing the ticket.

**Closed by kelson42** 2023-08-27 03:32 UTC
Labels: question
