### ISSUE TITLE
“Der Postillon” welcome page youtube video not scraped (properly)

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#40] opened 2020-10-26 21:34 UTC
See https://tukasu.ml/der-postillon.com_fr_all_2020-10/A/www.der-postillon.com/

**Comment by kelson42** [comment] 2020-10-26 21:35
Maybe a duplicate of https://github.com/openzim/zimit/issues/9?

**Comment by ikreymer** [comment] 2020-10-26 23:05
Hm, I thought it was just an image on the frontpage, and links to a page with videos: https://tukasu.ml/der-postillon.com_fr_all_2020-10/A/www.der-postillon.com/2020/10/alltagsdinge-video.html
The videos should all work on that page. Unfortunately, the home page has changed so hard to tell. I think all of the other youtube videos should be working..

**Comment by ikreymer** [comment] 2020-10-27 00:00
Most likely it was supposed to look like this, so the issue was with the image: https://www.der-postillon.com/search?q=5+allt%C3%A4gliche+Dinge%2C+deren+Zweck+nur+die+wenigsten+kennen+%5BVideo%5D

Maybe the image was unavailable for whatever reason. In the archived version, it was being linked to: https://i9.ytimg.com/vi/7CDSfGerDDw/maxresdefault.jpg?time=1603284600000&sqp=CPjcwPwF&rs=AOn4CLDiaz8sDQqqx8gYaGkrcZzCIV-pRA
Now, it is being linked to a local blog copy: https://1.bp.blogspot.com/-VsktYROTXnE/X5E0XzJhSHI/AAAAAAAA8Dk/URTnzYdyBj0K2tAhJTNPgSuNQxyecdJ7QCLcBGAsYHQ/s1280/maxresdefault.jpg

Closing, since the issue is not about video and probably an error on the site at the time. Not much we can do other than re-run the crawl.

**Closed by ikreymer** 2020-10-27 00:00 UTC
Labels: bug
