### ISSUE TITLE
Unable to find WARC record for main page

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#328] opened 2024-06-24 10:27 UTC
In [this zimit.kiwix.org run](https://farm.zimit.kiwix.org/pipeline/25f26c89-7f92-4f6e-a53b-35ff2c854912/debug), warc2zim fails on homepage

```
KeyError: 'Unable to find WARC record for main page: ZimPath(shamela.ws/book/30622), aborting'
```

The recipe has a very long/complicated include/exclude that apparently resulting in a single page crawl… but of that main page.

**Comment by rgaudin** [comment] 2024-06-24 10:36
Also:

- https://farm.zimit.kiwix.org/pipeline/bfa62cd6-36c1-445a-b110-5068e8566d96/debug
- https://farm.zimit.kiwix.org/pipeline/97caa814-1a42-4a7c-b5f7-6db96ab845c9/debug
- https://farm.zimit.kiwix.org/pipeline/6c8787cf-e6d4-475a-8631-552cb3bc6d10/debug
- https://farm.zimit.kiwix.org/pipeline/962a9881-54ab-40f9-af8f-527071857309/debug
- https://farm.zimit.kiwix.org/pipeline/8826288a-374a-4a38-b1fa-b8a8df3c963f/debug

**Comment by benoit74** [comment] 2024-06-24 11:47
Duplicate of https://github.com/openzim/warc2zim/issues/203

**Closed by benoit74** 2024-06-24 11:47 UTC
Labels: bug
