### ISSUE TITLE
[zimit1] scraper never exits

### ISSUE THREAD

**Issue by rgaudin** [openzim/zimit#295] opened 2024-04-25 12:22 UTC
[youzim.it run](https://farm.youzim.it/pipeline/69cd52e6-ab12-4d22-8302-e62e6e098e76/debug) never exited. Log seem to show that warc2zim completed and the container looks healthy but it never released the process

```
{"timestamp":"2024-04-21T00:09:40.923Z","logLevel":"info","context":"general","message":"Crawling done","details":{}}
{"timestamp":"2024-04-21T00:09:40.925Z","logLevel":"info","context":"general","message":"Exiting, Crawl status: done","details":{}}

----------
Processing WARC files in /output/.tmp7_do7xtj/collections/crawl-20240421000734622/archive
16 WARC files found
Calling warc2zim with these args: ['--name=commons.libretexts.org_0b5fb1f0', '--zim-file=commons.libretexts.org_0b5fb1f0.zim', '--publisher=openZIM', '--output', '/output', '--url', 'https://commons.libretexts.org/', '-v', '--progress-file', '/output/warc2zim.json', '/output/.tmp7_do7xtj/collections/crawl-20240421000734622/archive']
Resolve redirect
set index
```

```
 "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1807207,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-04-21T00:07:28.68249077Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
```

Note that `ExitCode` on docker inspect is `0` on running containers.

**Comment by benoit74** [comment] 2024-06-18 09:35
Duplicate of https://github.com/openzim/warc2zim/issues/132

**Closed by benoit74** 2024-06-18 09:35 UTC
Labels: bug, waiting_for_repro
