### ISSUE TITLE
DevDocs Table of content logos are missing

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#44] opened 2020-10-27 10:57 UTC
ZIM:
![image](https://user-images.githubusercontent.com/1029718/97292473-94068080-184b-11eb-9a4e-46708aff8c35.png)

Online:
![image](https://user-images.githubusercontent.com/1029718/97292519-a2549c80-184b-11eb-8ddb-35ac0bb2e5d0.png)

**Comment by ikreymer** [comment] 2020-10-27 14:46
What browser are you using? (I'm unable to repro this in either Chrome, Firefox or Safari on Mac)

**Comment by rgaudin** [comment] 2020-10-27 14:47
Works for me as well… 
<img width="321" alt="Screen Shot 2020-10-27 at 14 47 08" src="https://user-images.githubusercontent.com/57929/97317996-4e55b200-1863-11eb-8d2f-76776d48b448.png">

Let's close this until it gets reproduced.

**Closed by rgaudin** 2020-10-27 14:47 UTC
Labels: bug

**Comment by kelson42** [comment] 2020-10-27 15:03
Works for me as well, but I see this is now the latest version I have asked to rebuild earlier today.
