### ISSUE TITLE
Puppeteer errors causing program termination

### ISSUE THREAD

**Issue by MCSeekeri** [openzim/zimit#376] opened 2024-08-27 12:07 UTC
I was using Zimit to archive the SCP-CN Wikidot site and encountered an interruption of the program due to a puppeteer error.
Attached here is the log output before the program exits.
```
{"timestamp":"2024-08-27T08:36:03.741Z","logLevel":"warn","context":"behavior","message":"Waiting for custom page load failed","details":{"type":"exception","message":"Protocol error (Runtime.evaluate): Target closed","stack":"TargetCloseError: Protocol error (Runtime.evaluate): Target closed\n    at CallbackRegistry.clear (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)\n    at CdpCDPSession._onClosed (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:98:25)\n    at Connection.onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:127:25)\n    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:38:32)\n    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)\n    at WebSocket.onMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)\n    at WebSocket.emit (node:events:519:28)\n    at Receiver.receiverOnMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1220:20)\n    at Receiver.emit (node:events:519:28)\n    at Immediate.<anonymous> (/app/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:601:16)"}}
{"timestamp":"2024-08-27T08:36:03.742Z","logLevel":"warn","context":"links","message":"Link Extraction failed","details":{"type":"exception","message":"Attempted to use detached Frame '9A153325AAEA4D188BAEBA1E8B6B9D41'.","stack":"Error: Attempted to use detached Frame '9A153325AAEA4D188BAEBA1E8B6B9D41'.\n    at CdpFrame.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:92:23)\n    at file:///app/dist/crawler.js:1378:102\n    at Array.map (<anonymous>)\n    at Crawler.extractLinks (file:///app/dist/crawler.js:1378:72)\n    at Crawler.loadPage (file:///app/dist/crawler.js:1322:20)\n    at async Crawler.default [as driver] (file:///app/dist/defaultDriver.js:2:5)\n    at async Crawler.crawlPage (file:///app/dist/crawler.js:566:9)\n    at async PageWorker.crawlPage (file:///app/dist/util/worker.js:153:21)"}}
[zimit::2024-08-27 08:36:04,142] INFO:SIGINT/SIGTERM received, stopping zimit
```
```
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72
            throw new Error('Execution context was destroyed');
                  ^

Error: Execution context was destroyed
    at file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72:19
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1936:31
    at OperatorSubscriber2._this._next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:993:9)
    at Subscriber2.next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:696:12)
    at listener (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:367:24)
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:36:7
    at Array.map (<anonymous>)
    at Object.emit (file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:35:20)
    at EventEmitter.emit (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:77:23)
    at [nodejs.dispose] (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:151:23)
```
docker-compose.yml:
```
services:
  openzim:
    image: ghcr.io/openzim/zimit:dev
    environment:
      - HTTP_PROXY=http://100.100.2.2:19999
      - HTTPS_PROXY=http://100.100.2.2:19999
    command:
      - zimit
      - --url=https://scp-wiki-cn.wikidot.com
      - --keep
      - --name=scp-wiki_zh_all
      - --title="SCP 基金会 wiki"
      - --output=/output
      - --exclude=(\?q=|/signin|/forum|/system:)
      - --verbose
      - --workers=64
      - --behaviors=autoplay,autofetch,siteSpecific,autoscroll
      - --lang=zh
      - --zim-lang=zh
      - --description="SCP 基金会中国分部数据存档"
    volumes:
      - ./output:/output
 ```
I've modified the configuration with reference to the existing [recipes](https://farm.openzim.org/recipes/scp-wiki_en), but I still encounter this problem.

**Comment by benoit74** [comment] 2024-09-02 07:54
Puppeteer is the software driving the browser used to crawl the website. The error you get is a puppeteer error which seems to indicate that the browser is gone. Probably crashed. Using `--workers=64` means that there is 64 tabs running in parallel in the browser. I can easily imagine it can lead to weird situations either on browser side (out of memory issues, or simply weird browser crash due to parallelism of many many requests to same website) or on browsertrix crawler side (any parallelism bug). Not something that needs to be fixed at our level, and too hard to reproduce to open an issue on browsertrix crawler repo from my PoV.

**Comment by ikreymer** [comment] 2024-09-02 17:19
@MCSeekeri can you provide a more complete log of when this happened? After how many pages? We haven't been able to repro this type of error consistently, it could be browser running out of memory, or something else. Would also recommend trying with even less workers than 8, maybe 2 or 4.

**Comment by ikreymer** [comment] 2024-09-06 01:34
@MCSeekeri Unfortunately, no, this is very hard to reproduce because it takes 20K-30K pages before the issues pops up, and the stack trace is not helpful at all.

**Comment by ikreymer** [comment] 2024-09-06 02:55
> Is there any way to make the program “more verbose” to find the possible root cause of the problem? When testing on my server, it seems that having workers set too high doesn't affect the results, and it usually only takes a few hours of running to crawl 20K-30K pages and reproduce the problem.

Possibly, you can try adding this to the environment: `DEBUG=puppeteer:*` which should enable extensive puppeteer logging, see if that provides any additional info!

**Comment by ikreymer** [comment] 2024-09-06 03:13
You can try it with browsertrix-crawler image directly with the same command line: `docker run -e DEBUG="puppeteer:*" -v $PWD/crawls:/crawls -it webrecorder/browsertrix-crawler crawl --failOnFailedSeed --workers 2 --waitUntil load --url https://scp-wiki-cn.wikidot.com --depth -1 --timeout 180 --exclude "(ad-delivery|doubleclick|btloader|consent\\.nit|nitropay|onesignal|\\?q=|signup-landing\\?|\\?cid=|forum/t|:system|avn\\.sh|crom|/signin|:)" --lang zh --behaviors autoplay,autofetch,siteSpecific --behaviorTimeout 90 --diskUtilization 90 --url https://scp-wiki-cn.wikidot.com --userAgentSuffix +Zimit --mobileDevice Pixel-2`

**Comment by ikreymer** [comment] 2024-09-06 20:35
@MCSeekeri I think it's a bug in Puppeteer that happens when it's cleaning up some internal objects, I opened an issue there: https://github.com/puppeteer/puppeteer/issues/13056

**Comment by benoit74** [comment] 2024-09-07 05:47
Thank you @ikreymer for your support!

**Comment by ikreymer** [comment] 2024-09-27 18:37
This *might* be fixed in 1.3.1, see if you can repro this again in this version - again very tricky to repro, puppeteer folks think its something that's not being caught in the crawler, so added a bunch of extra exception handling improvements, which might address this.

**Comment by ikreymer** [comment] 2024-09-29 03:41
> A new error reporting ............ is kind of progress? Though I don't see any specific reason for it, after that I'll tone down the number of Workers and try again ...... [data.log](https://github.com/user-attachments/files/17177402/data.log)

Yeah, I think these errors are most certainly way too many workers!

**Comment by ikreymer** [comment] 2024-10-08 00:28
Can you try again with browsertrix-crawler:1.3.2? Just updated it with latest puppeteer, which should have more accurate stack trace according to: https://github.com/puppeteer/puppeteer/issues/13056#issuecomment-2397379703

**Comment by ikreymer** [comment] 2024-10-09 23:24
@MCSeekeri thanks for this - this is definitely a better stack trace, though still stumped exactly *why* its crashing there!
Can you try one more time with this branch: https://github.com/webrecorder/browsertrix-crawler/tree/link-extract-promise-improve

If it's easier, can do another release, but wanted to see if the changes there might fix this.

**Closed** 2024-10-11 07:11 UTC
