### ISSUE TITLE
liberius welcome page broken

### ISSUE THREAD

**Issue by kelson42** [openzim/zimit#161] opened 2022-10-09 09:58 UTC
Somehow it generates a redirect to the online homepage, but this redirect does not exists in the original web site. See
https://library.kiwix.org/liberius.net_fr_all_2022-10/A/www.liberius.net/

**Comment by rgaudin** [comment] 2022-10-10 07:56
Duplicate of #154

**Closed by rgaudin** 2022-10-10 07:56 UTC
Labels: bug, duplicate, question
